{% set python_min = '3.10' %}
{% set name = "cmeutils" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cmelab/cmeutils/archive/refs/tags/v.1.5.0.tar.gz
  sha256: 743a9c521f7298293848d0d94a9c365e71274377e3ccc6f24f7f19f27dcb9588

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0 

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - freud >=3.4
    - gmso >=0.14
    - fresnel >=0.13.5
    - gsd >=3.0
    - hoomd >=5.0
    - mbuild >=1.0
    - numpy >=2.0
    - pip
    - python >={{ python_min }},<=3.13
    - matplotlib-base
    - pymbar >=4.0
    - rowan

test:
  imports:
    - cmeutils
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/cmelab/cmeutils
  summary: 'Useful functions by and for the CME lab.'
  description: |
    Helpful functions used by the CME Lab.
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  doc_url: https://github.com/cmelab/cmeutils
  dev_url: https://github.com/cmelab/cmeutils

extra:
  recipe-maintainers:
    - jennyfothergill
    - chrisjonesBSU
    - marjanalbooyeh
